apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-data
  namespace: minecraft
spec:
  resources:
    requests:
      storage: "2048Mi"
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
