apiVersion: v1
kind: Service
metadata:
  name: minecraft-metrics
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9225"
spec:
  type: ClusterIP
  selector:
    app: minecraft-dep
  ports:
    - name: metrics
      port: 9225
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-svc
  namespace: minecraft
spec:
  type: NodePort
  selector:
    app: minecraft-dep
  ports:
  - name: minecraft-tcp
    port: 25565
    targetPort: 25565
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-udp
  namespace: minecraft
spec:
  type: LoadBalancer
  selector:
    app: minecraft-dep
  ports:
    - name: minecraft-udp
      port: 19132
      targetPort: 19132
      protocol: UDP
